# Generated by Django 4.2.1 on 2023-06-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_medication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.PositiveBigIntegerField(help_text='Enter the frequency in hours'),
        ),
    ]
