# Generated by Django 4.2.1 on 2023-06-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pharmacy_alter_medication_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
