# Generated by Django 4.2.1 on 2023-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_pharmacy_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='phoneNumber',
            field=models.CharField(max_length=12),
        ),
    ]
