# Generated by Django 4.2.1 on 2023-06-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_pharmacy_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='pharmacies',
            field=models.ManyToManyField(to='main_app.pharmacy'),
        ),
    ]
