# Generated by Django 4.2.1 on 2023-06-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_medication_frequency'),
        ('main_app', '0007_alter_pharmacy_phonenumber'),
    ]

    operations = [
    ]
