# Generated by Django 4.2.1 on 2023-06-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_medication_pharmacies'),
        ('main_app', '0008_merge_20230606_1831'),
    ]

    operations = [
    ]
